DECLARE @ID_PDC VARCHAR(12), @CAB VARCHAR(MAX), @ITEM VARCHAR(MAX), @ROD VARCHAR(MAX), @CODCLIENTE VARCHAR(20);

SET @ID_PDC = (SELECT TOP 1 PB.ID_PDC FROM PEDIDO_BIONEXO_ITEM PBI INNER JOIN PEDIDO_BIONEXO PB ON PBI.ID_PDC=PB.ID_PDC WHERE STATUS = 8  AND PBI.FATURAR=0 ORDER BY PBI.ID_PDC)
SET @CODCLIENTE = (SELECT CODCLIENTE FROM PEDIDO_BIONEXO WHERE ID_PDC=@ID_PDC)
SET @CAB = (SELECT DISTINCT 
	'01' AS CABECALHO
,	PB.ID_PDC AS PEDIDO_CLIENTE
,	C.TELEFONE2 AS CODCLIENTE
,	REPLACE(REPLACE(REPLACE(PB.CNPJ_CLIENTE,'.',''),'-',''),'/','') AS CNPJ_CLIENTE
,	'14222555000158' AS CNPJ_FORNECEDOR
,	(SUBSTRING(REPLACE(CONVERT(DATE,DT_CONFIRMACAO,103),'-',''),3,4) + SUBSTRING(REPLACE(CONVERT(DATE,DT_CONFIRMACAO,103),'-',''),1,4)) AS DATA
,	'0' AS PLANO_PAG
,	'0' AS END_ENTREGA
FROM PEDIDO_BIONEXO PB
left JOIN PEDIDO_BIONEXO_ITEM PBI ON PB.ID_PDC=PBI.ID_PDC
left JOIN CLIENTES C ON PB.CNPJ_CLIENTE=C.CPF_CNPJ
LEFT JOIN PRODUTOS P ON PBI.CODPRODUTO_EMPRESA=P.CODPRODUTO
WHERE PBI.STATUS=8 AND PBI.ID_PDC=@ID_PDC AND PBI.FATURAR=0 FOR XML PATH(''))

SET @ITEM = (SELECT
	'02' AS DETALHE
,	'5' AS TP_PROD
,	CODPRODUTO AS IDT_PROD
,	'0' AS COND_COM
,	SUBSTRING(PBI.UNIDADE,1,2) AS EMBALAGEM
,	CAST(PBI.QUANTIDADE AS DECIMAL(11,3)) AS QUANTIDADE
,	CAST(PBI.VR_UNITARIO AS DECIMAL(16,5)) AS VR_UNITARIO
,	'0' AS DESCONTO
,	'0' AS ICMS
,	'0' AS DESC_COM
FROM PEDIDO_BIONEXO PB
left JOIN PEDIDO_BIONEXO_ITEM PBI ON PB.ID_PDC=PBI.ID_PDC
left JOIN CLIENTES C ON PB.CNPJ_CLIENTE=C.CPF_CNPJ
LEFT JOIN PRODUTOS P ON PBI.CODPRODUTO_EMPRESA=P.CODPRODUTO
WHERE PBI.STATUS=8 AND PBI.ID_PDC=@ID_PDC AND PBI.FATURAR=0 FOR XML PATH(''))

SET @ROD = (SELECT
	'03' AS REGISTRO
,	COUNT(ID_PDC_ITEM) AS TOTAL_ITEM
,	SUM(QUANTIDADE) AS TOTAL_QTDE
,	SUM(PBI.VR_TOTAL) AS TOTAL_NOTA
,	'0' AS OBS1
,	'0'	AS OBS2
FROM PEDIDO_BIONEXO PB
LEFT JOIN PEDIDO_BIONEXO_ITEM PBI ON PB.ID_PDC=PBI.ID_PDC
LEFT JOIN CLIENTES C ON PB.CNPJ_CLIENTE=C.CPF_CNPJ
LEFT JOIN PRODUTOS P ON PBI.CODPRODUTO_EMPRESA=P.CODPRODUTO
WHERE PBI.STATUS=8 AND PBI.ID_PDC=@ID_PDC AND PBI.FATURAR=0 FOR XML PATH(''))

SELECT @CAB
SELECT @ITEM
SELECT @ROD

INSERT INTO TESTE (ID_PDC, XML, CODCLIENTE) SELECT @ID_PDC, @CAB, @CODCLIENTE
INSERT INTO TESTE1 (ID_PDC, XML, CODCLIENTE) SELECT @ID_PDC, @ITEM, @CODCLIENTE
INSERT INTO TESTE2 (ID_PDC, XML, CODCLIENTE) SELECT @ID_PDC, @ROD, @CODCLIENTE
SELECT * FROM TESTE
SELECT * FROM TESTE1
SELECT * FROM TESTE2

UPDATE PEDIDO_BIONEXO_ITEM SET FATURAR=1 WHERE ID_PDC=@ID_PDC AND STATUS = 8
UPDATE PEDIDO_BIONEXO_ITEM SET INTEGRACAO=1 WHERE ID_PDC=@ID_PDC AND STATUS = 8
UPDATE TESTE SET INTEGRADO = 1 WHERE ID_PDC=@ID_PDC
/*
TRUNCATE TABLE TESTE
TRUNCATE TABLE TESTE1
TRUNCATE TABLE TESTE2
*/

DELETE FROM TESTE2 WHERE ID NOT IN (9,16)
